### PR TITLE
feat: impersonate flow activation/connection

### LINKED ISSUE #47: Connect connection references and activate flows as an application user
## Is your feature request related to a problem? Please describe
The production environment we deploy to has conditional access policies that prevent us from doing any of our deployment as a licensed user - the current workaround for not being able to connect and and activate flows with an application user. 

## Describe the solution you'd like
I've done a quick test and it looks like it's possible to activate flows as an application user _impersonating_ a licensed user. This avoids the need to authenticate as the licensed user altogether.

### PR DESCRIPTION
**Pull request by ewingjm**
## Purpose
Resolves #47. Allows the use of an application user when connecting/activating flows.

## Approach
Uses the `LicensedUsername` runtime setting to impersonate a user that owns the connections and is licensed for flows.

## TODOs
- [x] Automated test coverage for new code
- [x] Documentation updated (if required)
- [x] Build and tests successful

### CODE REVIEW

**Comment by tdashworth** [comment]
@ewingjm thanks for the contribution. None of your PRs are small... 

Don't worry about the 10 code smells, lets discuss that elsewhere since it's not regarding this PR. 

A couple of thoughts:
- with the move to the new `Execute method, I think some methods have become redundant which should be removed. The code coverage shows this and should improve this to the 80% target. 
- since there are two uses of trying the given username and falling back to the deployment user, might I be a good idea to add a shared method for that?

**Comment by ewingjm** [comment]
Hey, @tdashworth. I think the 10 code smells was due to my change - I added a `Fields` static class that sat above the individual entity classes for common fields. I wasn't actually using it, so I took it out. I've refactored so that the fallback logic is shared and removed the redundant `ExecuteMultiple` extension method.

The low code coverage is coming from the `CrmServiceAdapter` which already has pretty low coverage as we haven't been able to mock `CrmServiceClient`. It's complaining about the negative testing and error handling, so I think we need a new integration test fixture for `CrmServiceAdapter` that doesn't rely on deploying the package successfully to test these negative scenarios.

**Comment by ewingjm** [comment]
Just updating the README now @tdashworth and should be good to go.

**Review by tdashworth — APPROVED** [review]
Looks good. Thank you 😄

**Pull request merged**
