### PR TITLE
fix: exception when multiple processes configured

### LINKED ISSUE #21: Workflows Activation and Deactivation does not work for multiple workflows
## Describe the bug
When you add more items in this section then it fails with an error

## To reproduce

Add more than one workflow in the config file eg:
  <processestodeactivate>
    <processtodeactivate>Process name 1</processtodeactivate>
    <processtodeactivate>Process name 2</processtodeactivate>
  </processestodeactivate>
or
  <processestoactivate>
    <processtoactivate>Process name 1</processtoactivate>
    <processtoactivate>Process name 2</processtoactivate>
  </processestoactivate>

and you will get an exception - there is a bug in this.QueryWorkflowsByName method used in both above scenarios

## Expected behaviour
Expected behavior is to get all the workflows Activated or Deactivated, depends what section it is.

## Screenshots
None

## Environment (please complete the following information):
 - Version Latest
 - Power Apps environment version

## Additional context
None

### PR DESCRIPTION
**Pull request by ewingjm**
## Purpose
Resolves #21.

## Approach
Replaces `QueryByAttribute` which was not suitable for the query being done with `QueryExpression`.

## TODOs
- [x] Automated test coverage for new code
- [x] Documentation updated (if required)
- [x] Build and tests successful

### CODE REVIEW

**Comment by tdashworth** [comment]
Thanks for the quick fix @ewingjm! 

Looks like the tests are failing because the mocks haven't been updated. They are currently expecting a `QueryByAttribute` object which you've obviously replaced. This applies for: 
- `Activate_QueryForProcesses_IncludesAllNamesPassed`
- `Activate_FaultWhenSettingsStatus_LogErrors`
- `Deactivate_QueryForProcesses_IncludesAllNamesPassed`
- `Deactivate_FaultWhenSettingsStatus_LogErrors`

I'm not sure the root cause why both `PackageTemplateBase_FlowsInPackage_AreActiveAccordingToConfig` tests are failing.

**Comment by ewingjm** [comment]
> Thanks for the quick fix @ewingjm!
> 
> Looks like the tests are failing because the mocks haven't been updated. They are currently expecting a `QueryByAttribute` object which you've obviously replaced. This applies for:
> 
> * `Activate_QueryForProcesses_IncludesAllNamesPassed`
> * `Activate_FaultWhenSettingsStatus_LogErrors`
> * `Deactivate_QueryForProcesses_IncludesAllNamesPassed`
> * `Deactivate_FaultWhenSettingsStatus_LogErrors`
> 
> I'm not sure the root cause why both `PackageTemplateBase_FlowsInPackage_AreActiveAccordingToConfig` tests are failing.

Yep, unit tests slipped my mind on this one - only ran the two integration tests locally that I thought had been affected. About to push the fix to the unit tests.

**Review by tdashworth — APPROVED** [review]
Looks good!

**Comment by ewingjm** [comment]
> Looks good!

Not sure what fixed the integration tests - maybe I was running them locally at the same time? 😅

**Pull request merged**
