### PR TITLE
fix: redundant requests when setting states

### PR DESCRIPTION
**Pull request by ewingjm**
## Purpose
Requests are made to activate or deactivate processes and SDK steps even when they are already at the desired state.

## Approach
Only requests to change the state when the state is different to the desired state. In addition, use ExecuteMultiple requests to avoid excessive chattiness.

## TODOs
- [x] Automated test coverage for new code
- [x] Documentation updated (if required)
- [x] Build and tests successful

### CODE REVIEW

**Comment by tdashworth** [comment]
Lots of failed tests 😢 but otherwise happy to approve once resolved.

**Comment by ewingjm** [comment]
> Lots of failed tests 😢 but otherwise happy to approve once resolved.

Think our CI environment has long since been deleted due to other people using the tenant capacity 😄

**Comment by tdashworth** [comment]
> > Lots of failed tests 😢 but otherwise happy to approve once resolved.
> 
> Think our CI environment has long since been deleted due to other people using the tenant capacity 😄

Ah yes...

**Comment by ewingjm** [comment]
Hi @tdashworth. I think this is ready now!

**Review by tdashworth — APPROVED** [review]

**Comment by tdashworth** [comment]
@ewingjm it looks like we broke the release version reference....

image

**Comment by ewingjm** [comment]
> @ewingjm it looks like we broke the release version reference....

My bad. Resolved in #77.

**Pull request merged**
